### ISSUE TITLE
custom validation function

### ISSUE THREAD

**Issue by dalssoft** [herbsjs/gotu#2]
It should be possible to create custom validations functions and validate the entity by calling `validate()` only

this:

```javascript
const User = 
    entity('User', {
        name: field(String),
        lastAccess: field(Date),
        accessCount: field(Number),
        hasAccess: field(Boolean),
        plan: field(Plan),
        validations:[
        	function validateBla () {
        	},
        	function validateFoo () {
        	}
        ]
    })
```

or something like this

```javascript
const User = 
    entity('User', {
        name: field(String, validation: () => { this.name === "John" } ),
        lastAccess: field(Date),
        accessCount: field(Number),
        hasAccess: field(Boolean),
        plan: field(Plan),
    })
```

**Comment by endersoncosta** [comment]
I belive that the best way is the first approach, because of being cleaner. But I also believe that the entity should be validated when it is instantiated, thus isValid would always be correct and the main form of validation.

**Comment by dalssoft** [comment]
Some inspiration:

https://guides.rubyonrails.org/active_record_validations.html#custom-methods
