### ISSUE TITLE
Date type fields, getting 'Invalid Date', when object is created by fromJSON

### ISSUE THREAD

**Issue by m7vicente** [herbsjs/gotu#3]
When a new object is create by 'fromJSON', undefined Date type fields  are getting 'Invalid Date' value,
this error probly is caused by passing undefined value in Date type constructor.

![DateInvalid](https://user-images.githubusercontent.com/25369499/78506938-8eccd180-7753-11ea-8529-150c9cae1bc3.gif)

**Comment by m7vicente** [comment]
Changing tests, from pull requests #4, I discovered another error in fromJSON.

If a undefined entity as passed, he build a new instance from JSON (the same method is calling), but value is undefined, so then he try access the attribute of undefined occurs an error.

![Invalid entity](https://user-images.githubusercontent.com/25369499/78680769-4bdd3c00-78c2-11ea-9333-2edb0c127635.gif)

I try addinting a validation in parse, to check if data has value, case null he return undefined, but i think can change comportament on application. like a undefid boolean will get undefaid value insted of false.

![Invalid entity solution](https://user-images.githubusercontent.com/25369499/78680972-8a72f680-78c2-11ea-8bc5-6315b4f50eb7.gif)

**Comment by dalssoft** [comment]
I think PR https://github.com/herbsjs/gotu/pull/4 and https://github.com/herbsjs/gotu/pull/5 fix both bugs. I'm closing this issue
