### ISSUE TITLE
ID field

### ISSUE THREAD

**Issue by dalssoft** [herbsjs/gotu#46]
In order to improve metadata about which fields represent the IDs of an entity it would be possible to declare as field like:

```js
const Customer = 
    entity('Customer', {
        id: id(Number),    <---- id definition
        name: field(String),
        isVIP() {
            ...
        }
    })
```

for composite IDs (ex: id + SSN):

```js
const Customer = 
    entity('Customer', {
        id: id(Number),    <---- id definition
        SSN: id(Number),    <---- id definition
        name: field(String),
        isVIP() {
            ...
        }
    })
```

metadata:

```js
Customer.prototype.meta.schema.id.isID //true
Customer.prototype.meta.schema.SSN.isID //true
```

This would help in:
- CLI: better use case generation
- 2Knex: better repository generation (no ID info required)
- 2REST and 2GQL: better resolver code

**Comment by dalssoft** [comment]
@italojs 
> what do you think about we have an "uuid" type too?

you can already use `default` for that.


```js
const { field, id, UUID } = require('@herbs/herbs') // gotu

const Customer = 
    entity('Customer', {
        id: id(String, , { default: () => new UUID() }),    <---- uuid id definition
        
    })
```

**Comment by jhomarolo** [comment]
I agree with @dalssoft, we already have this possibility with default.

**Comment by italojs** [comment]
this issue make match with this feature https://github.com/herbsjs/herbs2knex/issues/23

**Comment by dalssoft** [comment]
One more thing. the code below should have the same behavior: 

```js
const Customer = 
    entity('Customer', {
        id: id(Number),    <---- id definition
        ...
    })
```

And

```js
const Customer = 
    entity('Customer', {
        id: field(Number, isID: true),    <---- id definition
        ...
    })
```

So `id(...)` is just a alias to `field(..., isID:true)`

**Comment by maikvortx** [comment]
I agree with you @dalssoft!
