### ISSUE TITLE
Shorthand to access ids e fields metadata

### ISSUE THREAD

**Issue by euduardo** [herbsjs/gotu#60]
**Is your feature request related to a problem? Please describe.**
It would be nice to have an API to access the Ids and Fields metadata from an entity.

You can already access those metadata, but the API is not user friendly.

For example, to check if an property is an id, it is the necessary code:
```js
const User = entity('User', {
    id: id(Number),
   name: field(String)
})

const user = new User()

const isId = user.__proto__.meta.schema.id.options.isId
```

**Describe the solution you'd like**
I would like to access those fields from a static field or method in the entity class. Something like:
```js
const User = entity('User', {
    id: id(Number),
   name: field(String)
})

const userIds = User.schema.ids
const userFields = User.schema.fields
``` 

**Additional context**
There are some open issues that could use this feature without reimplementing it again.

**Comment by italojs** [comment]
the discussion will continue on https://github.com/herbsjs/gotu/pull/57

**Comment by dalssoft** [comment]
It is ok to keep the discussion on the PR, but since it is still a unfinished PR with a on going discussion I will keep this issue open until we have it finished.

**Comment by jhomarolo** [comment]
Completed with #57
